<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-01 17:28
=======
# Generated by Django 4.0.2 on 2022-03-03 05:13
>>>>>>> 9d245a7e128456c6eb50a5f626fec1df7c1678c1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=80)),
                ('max_leaves', models.IntegerField(default=31)),
                ('leaves_remaining', models.FloatField(default=31)),
                ('is_a_line_manager', models.BooleanField(default=False)),
                ('line_manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='myapp.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('include_sat_sun', models.BooleanField(default=False)),
<<<<<<< HEAD
=======
                ('half_day_morning_shift', models.BooleanField(default=True)),
                ('half_day_evening_shift', models.BooleanField(default=True)),
>>>>>>> 9d245a7e128456c6eb50a5f626fec1df7c1678c1
                ('is_leave_pending', models.BooleanField(blank=True, default=True, null=True)),
                ('is_leave_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_leave_rejected', models.BooleanField(blank=True, default=False, null=True)),
                ('is_leave_cancelled', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelation Approved', 'Cancelation Approved'), ('Cancelation Rejected', 'Cancelation Rejected'), ('Cancelation Pending', 'Cancelation Pending')], default='Pending', max_length=50)),
                ('reason', models.TextField(default=' ', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='myapp.employee')),
            ],
        ),
    ]
