# Generated by Django 4.0.2 on 2022-03-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leaves_remaining',
            field=models.PositiveIntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='employee',
            name='max_leaves',
            field=models.PositiveIntegerField(default=31),
        ),
    ]
