# Generated by Django 4.0.2 on 2022-02-16 07:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=80)),
                ('max_leaves', models.IntegerField(default=31)),
                ('leaves_remaining', models.IntegerField(default=31)),
                ('is_a_line_manager', models.BooleanField(default=False)),
                ('line_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 12, 39, 9, 502037)),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
