# Generated by Django 2.1.7 on 2022-02-17 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_leave_is_leave_approved_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_leave_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 13, 25, 46, 901170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
