# Generated by Django 4.0.2 on 2022-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_leave_from_date_alter_leave_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
