# Generated by Django 4.0.2 on 2022-03-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_leaves_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='half_day_end',
            field=models.BooleanField(default=False, verbose_name='Half Day End'),
        ),
        migrations.AddField(
            model_name='leave',
            name='half_day_start',
            field=models.BooleanField(default=False, verbose_name='Half Day Start'),
        ),
    ]
