# Generated by Django 4.0.2 on 2022-03-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_leave_half_day_end_leave_half_day_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='half_day_end',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='half_day_start',
        ),
        migrations.AlterField(
            model_name='employee',
            name='leaves_remaining',
            field=models.FloatField(default=31),
        ),
        migrations.AlterField(
            model_name='employee',
            name='max_leaves',
            field=models.IntegerField(default=31),
        ),
    ]
