# Generated by Django 4.0.2 on 2022-02-18 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_leave_status_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 6, 11, 12, 80994, tzinfo=utc)),
        ),
    ]
