# Generated by Django 4.0.2 on 2022-02-16 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_alter_user_date_joined_leave_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='line_manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 18, 54, 11, 182374)),
        ),
    ]
