# Generated by Django 2.1.7 on 2022-02-17 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220217_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 13, 27, 8, 186908, tzinfo=utc)),
        ),
    ]
