# Generated by Django 4.0.2 on 2022-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_leave_is_leave_cancelled_leave_is_leave_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelation Approved', 'Cancelation Approved'), ('Cancelation Rejected', 'Cancelation Rejected'), ('Cancelation Pending', 'Cancelation Pending')], default='Pending', max_length=50),
        ),
    ]
