# Generated by Django 4.0.2 on 2022-02-16 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employee_line_manager_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='line_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 19, 10, 8, 137938)),
        ),
    ]
