# Generated by Django 4.0.2 on 2022-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_leave_half_day_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='max_leaves',
            field=models.FloatField(default=31),
        ),
    ]
