# Generated by Django 4.0.2 on 2022-02-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_leave_status'),
        ('myapp', '0005_alter_leave_status'),
    ]

    operations = [
    ]
