# Generated by Django 4.0.2 on 2022-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_0004_alter_leave_status_0005_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelation Approved', 'Cancelation Approved'), ('Cancelation Rejected', 'Cancelation Rejected'), ('Cancelation Pending', 'Cancelation Pending')], default='Pending', max_length=50),
        ),
    ]
