# Generated by Django 4.0.2 on 2022-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='include_sat_sun',
            field=models.BooleanField(default=False),
        ),
    ]
